### ISSUE TITLE
Error: There is no row at position 25?

### ISSUE THREAD

**Issue by fuserlimon** [martinkabe/RSQLS#18] opened 2019-08-05 18:19 UTC
A lot of times, I do not understand what certain error mean during the push_data():

> push_data(cs, Table,"[db].[Table]", append = FALSE, showprogress = TRUE)
[1] "Data Frame has 27600 rows and 25 columns."

Pushing data into [db].[Table] table with showing progress
Pipe is used as separator.
Cleaning table [db].[Table]
Table [db].[Table] has been cleaned
There is no row at position 25.
This operation took
Minutes: 0
Seconds: 0
Milliseconds: 815.38

The table has 25 columns. I can't figure out what this error means. Please help.

**Comment by martinkabe** [comment] 2019-08-07 19:05
Could you let me know what RSQLS version do you have? You should reinstall if you have older than 2.8. The second option is sharing first 25 (coded) records from your data.frame so that I can reproduce this error.

**Comment by fuserlimon** [comment] 2019-08-07 19:43
Thank you! I reinstalled the package. The problem persists. The things is that 25 here refers to the number of columns. Because when I remove one column, the error says no row at position 24. So it is not row 25 if that makes sense. 

Also, what do you mean by 25(coded) records? I didn't understand.

**Comment by martinkabe** [comment] 2019-08-07 20:44
Could you send me “CREATE” table statement and few dummy records so that I can reproduce it?
    	
    	

    	Get Outlook for iOS
    
  




On Wed, Aug 7, 2019 at 9:43 PM +0200, "Adnan Hajizada" <notifications@github.com> wrote:












Thank you! I reinstalled the package. The problem persists. The things is that 25 here refers to the number of columns. Because when I remove one column, the error says no row at position 24. So it is not row 25 if that makes sense.


Also, what do you mean by 25(coded) records? I didn't understand.

**Comment by martinkabe** [comment] 2019-08-07 21:20
Can you also try append = TRUEparam in push_data method?
    	
    	

    	Get Outlook for iOS
    
  




On Wed, Aug 7, 2019 at 10:44 PM +0200, "martinkabe" <martinkabe@seznam.cz> wrote:











  
  
  
    
    	Could you send me “CREATE” table statement and few dummy records so that I can reproduce it?
    	
    	

    	Get Outlook for iOS
    
  




On Wed, Aug 7, 2019 at 9:43 PM +0200, "Adnan Hajizada" <notifications@github.com> wrote:












Thank you! I reinstalled the package. The problem persists. The things is that 25 here refers to the number of columns. Because when I remove one column, the error says no row at position 24. So it is not row 25 if that makes sense.


Also, what do you mean by 25(coded) records? I didn't understand.

**Comment by fuserlimon** [comment] 2019-08-07 21:59
I have tried append = TRUE. Same Error. 

Here's my CREATE code:

send_SQL_task(cs, "CREATE TABLE [db].[Table] (
  A int NOT NULL,
  B varchar(250),
  C varchar(255),
  D varchar(255),
  E varchar(255),
  F varchar(255),
  G varchar(255),
  H int,
  I varchar(255),
  J varchar(255),
  K varchar(255),
  L varchar(255),
  M varchar(255),
  N float,
  O float,
  P varchar(255),
  Q int,
  R varchar(255),
  S int,
  T int,
  U varchar(MAX),
  V varchar(500),
  W varchar(255),
 X varchar(255),
  Y varchar (255))")

Here is the 30 rows of coded data:
[TableToPush.xlsx](https://github.com/martinkabe/RSQLS/files/3479058/TableToPush.xlsx)

**Comment by martinkabe** [comment] 2019-08-08 07:14
I created db schema under my testing database, created table in the same manner like you have and tried push the data you sent me. It works for me without any issues.

Could you try that under different schema? E.g. dbo. I'm not sure why it is failing in your case, I cannot reproduce the error you are getting.

Pushing data into [db].[Table] table with showing progress
Pipe is used as separator.
Cleaning table [db].[Table]
Table [db].[Table] has been cleaned
29 records imported
This operation took
Minutes: 0
Seconds: 0
Milliseconds: 24.4676

**Comment by fuserlimon** [comment] 2019-08-08 14:08
Thank you sir. It is probably some problem on my end. Can you at least let me know what the error means? There is no row at position 25? Does this mean the 25th row is missing?

**Comment by martinkabe** [comment] 2019-08-08 14:20
To me sounds like if you have an array [0..24] and you are trying to access 25th item. But really not sure why this failing on your end. I would try with different schema. If not works then e.g. only for few records df <- dfOriginal[1:5,]. If you solve it, just let me know what did the trick. If it is something I could handle in my code then I'm gonna do that :-)

**Comment by fuserlimon** [comment] 2019-08-08 14:43
Thank you. I used your advice and went investigating row by row, eventually finding where the problem was. It was the data problem. The package work well.

**Comment by fuserlimon** [comment] 2019-08-08 14:44
It was a pipe symbol. '|' in the table. And since pipes are used to indicate separations, it gave an error.

**Comment by martinkabe** [comment] 2019-08-08 14:50
Oh I see. that's how push method is defined in default:
```
push_data(connString, df, sqltabname, append = TRUE, showprogress = FALSE, quotes = "auto", separator = '|')
```
If you have anywhere pipe in your data set, then try different one, e.g. caret delimiter - change in push method: separator = "^"

**Comment by martinkabe** [comment] 2019-08-08 14:51
Glad you solved it.

**Comment by martinkabe** [comment] 2019-08-08 14:51
I'm closing an issue since this is fixed and clarified.

**Closed as completed by martinkabe** 2019-08-08 14:51 UTC
